### ISSUE TITLE
Singulrity mode for nextflow pipeline

### ISSUE THREAD

**Issue by KeyTals** [tdelhomme/ITH_pipeline#2]
Is it possible to have singularity option? On HPCs, Singulairty is preferred method over docker due to sudo privilege issues.

Keyur

**Comment by nalcala** [comment]
Hi @KeyTals , you are right, and we will certainly do it. For now the pipeline is still in progress. Note that because it currently includes Hatchet for multi-sample CNV calling, which relies on gurobi libraries that require a license, the singularity image will not be able to contain everything and you will still need to set up things manually... 

Best,

Nicolas
